@host  = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImFkZHJlc3MiOiIweDgwOEYwODZFN2NkOWUzNDRiNDM5NzUxODA2N2M1NDNBNmFGMTk1QzEiLCJpYXQiOjE3Mjk4NTIwNzUsImV4cCI6MTcyOTkzODQ3NX0.f-3eMNBBBsyQ1-aeS8esTJGbX6ZFUDEi7nzSgvoPFvc
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImFkZHJlc3MiOiItMFg0ZWZmb2k2eTBzajEzNjJiZjViams3aDA1bGs0bnNqa3lmOWZ3emQiLCJpYXQiOjE3Mjk3MzYwMjQsImV4cCI6MTcyOTgyMjQyNH0.BJ2_2bgMRKJPcZAHZvmrvX6SBM2cbOysdQAe5nt_ZaU
### main route
GET {{host}}/


### test user: Create test user with random wallet address as fast as possible,
POST {{host}}/auth/test
Content-Type: application/json

{
    "address": "0x808F086E7cd9e344b4397518067c543A6aF195C1"
}

### Auth sign in info
POST {{host}}/auth/message
Content-Type: application/json

{
    "address": "0x32Be343B94f860124dC4fEe278FDCBD38C102D88"
}


### Send verificaiton code
POST {{host}}/auth
Content-Type: application/json

{
    "message": "myemasilgmail.com",
    "signature": "Whasr",
    "address": "0x6662153131313431831416841"
}

### Complete registeration
POST {{host}}/user/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "myemasil@gmail.com",
    "name": "Whasr"
}

### Update user
PATCH {{host}}/user/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "myemsasil@gmail.com",
    "name": "Whasr",
    "avatar": "https://whatever.com"
}


### Get dream mine game rules
GET {{host}}/dream-mine/rules
Authorization: Bearer {{token}}


### Place bet on dream mine game
POST {{host}}/dream-mine/bet
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "betAmount": 100,
    "mode": "EASY",
    "rows": 8,
    "token": "USDT",
    "chainId": 137
}

### Mine current row
POST {{host}}/dream-mine/mine/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "choice": 2
}

### Backoff mining and get the stake
POST {{host}}/dream-mine/backoff/9
Authorization: Bearer {{token}}
Content-Type: application/json


### Get current user's dream mine game history
GET {{host}}/dream-mine?status=FINISHED
Authorization: Bearer {{token}}


### Get current user's dream mine game history
GET {{host}}/dream-mine/is-playing
Authorization: Bearer {{token}}


### Get users
GET {{host}}/user/balance/WUSDC?chain=11155111
Authorization: Bearer {{token}}

### Request withdraw
POST {{host}}/user/withdraw
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "token": "WUSDC",
    "amount": 50,
    "chain": 11155111
}