@host2 = http://143.198.187.60
@host  = http://localhost:8000
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImFkZHJlc3MiOiItMFg5YjY3d3BiOHA3cWc5OXdqODUyNjgzOHMwNTh0Nm04dmVlZDRqMzEiLCJpYXQiOjE3Mjc3MzgyOTcsImV4cCI6MTcyNzc0NTQ5N30.UeXw0Uk4VCmSbIN2dJLpRuJPKEDQOoiis5Wk--SJio0
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImFkZHJlc3MiOiItMFg2anM3eDUxNzk3anliMnFneTd0aDUxZTZkMjZqcjMzMjd2dTQ4cHMiLCJpYXQiOjE3MjgzNDgzMDMsImV4cCI6MTcyODM1NTUwM30.HzD45_UagvJM0GgR2Stj4rJCZNGZ3m5iDMrXkJK1qzQ

### main route
GET {{host}}/


### test user: Create test user with random wallet address as fast as possible,
POST {{host}}/auth/test


### Auth sign in info
POST {{host}}/auth/message
Content-Type: application/json

{
    "address": "0x32Be343B94f860124dC4fEe278FDCBD38C102D88"
}


### Send verificaiton code
POST {{host}}/auth
Content-Type: application/json

{
    "message": "myemasilgmail.com",
    "signature": "Whasr",
    "address": "0x6662153131313431831416841"
}

### Get users
GET {{host}}/user/balance/USDT?chain=137
Authorization: Bearer {{token}}

### Complete registeration
POST {{host}}/user/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "myemasil@gmail.com",
    "name": "Whasr"
}

### Update user
PATCH {{host}}/user/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "myemsasil@gmail.com",
    "name": "Whasr",
    "avatar": "https://whatever.com"
}


### Get dream mine game rules
GET {{host}}/dream-mine/rules
Authorization: Bearer {{token}}


### Place bet on dream mine game
POST {{host}}/dream-mine/bet
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "betAmount": 10,
    "mode": "EASY",
    "rows": 8,
    "token": "USDT",
    "chainId": 137
}

### Mine current row
POST {{host}}/dream-mine/mine/12
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "choice": 2
}