@host  = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImFkZHJlc3MiOiItMFg4OWdveDZiZW41ZjE1Y2QwNTJmYTUwZ283MnJyd21qc3kxNGszNWoiLCJpYXQiOjE3Mjg1MjI2MDgsImV4cCI6MTcyODYwOTAwOH0.5Y037xn-FUZAmfL1EkmFqtL71PkmpMKe9_dRajMuotw
### main route
GET {{host}}/


### test user: Create test user with random wallet address as fast as possible,
POST {{host}}/auth/test


### Auth sign in info
POST {{host}}/auth/message
Content-Type: application/json

{
    "address": "0x32Be343B94f860124dC4fEe278FDCBD38C102D88"
}


### Send verificaiton code
POST {{host}}/auth
Content-Type: application/json

{
    "message": "myemasilgmail.com",
    "signature": "Whasr",
    "address": "0x6662153131313431831416841"
}

### Get users
GET {{host}}/user/balance/USDT?chain=137
Authorization: Bearer {{token}}

### Complete registeration
POST {{host}}/user/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "myemasil@gmail.com",
    "name": "Whasr"
}

### Update user
PATCH {{host}}/user/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "myemsasil@gmail.com",
    "name": "Whasr",
    "avatar": "https://whatever.com"
}


### Get dream mine game rules
GET {{host}}/dream-mine/rules
Authorization: Bearer {{token}}


### Place bet on dream mine game
POST {{host}}/dream-mine/bet
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "betAmount": 100,
    "mode": "EASY",
    "rows": 8,
    "token": "USDT",
    "chainId": 137
}

### Mine current row
POST {{host}}/dream-mine/mine/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "choice": 2
}

### Backoff mining and get the stake
POST {{host}}/dream-mine/backoff/9
Authorization: Bearer {{token}}
Content-Type: application/json


### Get current user's dream mine game history
GET {{host}}/dream-mine?status=FINISHED
Authorization: Bearer {{token}}


### Get current user's dream mine game history
GET {{host}}/dream-mine/is-playing
Authorization: Bearer {{token}}

