export enum EthereumChainsEnum {
  ETHEREUM_MAINNET = 1,
  BINANCE_SMART_CHAIN_MAINNET = 56,
  POLYGON_MAINNET = 137,
  AVALANCHE_MAINNET = 43114,
  FANTOM_OPERA_MAINNET = 250,
  ARBITRUM_ONE = 42161,
  OPTIMISM = 10,
  GNOSIS_XDAI = 100,
}
